### ISSUE TITLE
Can I combine PublishSubject and Observable inside the combineLatest method?

### ISSUE THREAD

**Issue by Guferos** [DeclarativeHub/Bond#561]
Hi, I am not sure if I am doing something wrong or it's a bug. I have the following code:
```
        let string = Observable("test")
        let subject = SafePublishSubject<Void>()
        
        combineLatest(string, subject)
            .observeNext(with: { _ in
                print("changed")
            })
        
        string.value = "test2"
        // Nothing happens after changing the string
        
        subject.next()
        // prints "changed"
``` 
Can someone help me to understand why there is no signal when I change the string value? Can I use `SafePublishSubject` together with `Observable` in the `combineLatest` method?

**Comment by srdanrasic** [comment]
`combineLatest` needs both signals to emit at least one event, otherwise there is nothing to combine. Because Subject does not have a concept of current value, there is nothing to emit until you explicitly send something with `next` method. This differs from Property/Observable which emits its current value when you start observing it. 

Your code is fine and the behavior is correct, but I guess you were expecting something else? What’s the problem you are solving?

**Comment by Guferos** [comment]
I wanted to execute the same chunk of code whenever my Observable emits a next event or when there is an event from the Subject. I didn't want to wrap the code into a function and I was looking for a way to combine both so I could put my code into one `observeNext` block. I've changed the `PublishSubject` to `Observable` and I made it work:
```
        let string = Observable("test")
        let subject = Observable<Void>(())
        
        combineLatest(string, subject)
            .observeNext(with: { _ in
                print("changed")
                ...
                // Here I have a large chunk of code that needs to be executed
                // either on string or subject next event.
            })
        
        string.value = "test2"
        // prints "changed"
        
        subject.next()
        // prints "changed"
```
Still unsure though if this is a proper way of handling my case.

**Comment by srdanrasic** [comment]
There is a couple of other ways, depending on what you need.

You could have subject start with a given element. Since you are working with Void type, you can just start the signal with `()`:

```swift
let string = Observable("test")
let subject = SafePublishSubject<Void>()

combineLatest(string, subject.start(with: ()))
    .observeNext  { string, _ in
        print(string)
    }
```

You could achieve the same with `replayLatest` operator. It will re-emit the latest string event when the subject emits an event. It's a bit more descriptive that above:

```swift
let string = Observable("test")
let subject = SafePublishSubject<Void>()

string.replayLatest(when: subject)
    .observeNext  { string in
        print(string)
    }
```

If the code within `observeNext` does not work/depend on the string value, you could use merge operator. Merge operator works on the signals with same type of elements, so you either need to convert String observable into Void or Void subject into String. You can use `map` for that:

```swift
let string = Observable("test")
let subject = SafePublishSubject<Void>()

merge(string.map { _ in }, subject)
    .observeNext {
        // note no event element (string) in this case
    }
```

**Comment by Guferos** [comment]
Thanks for the very detailed answer. I end up using the `start(with:)` method.
