### ISSUE TITLE
Custom UITableViewCell from xib

### ISSUE THREAD

**Issue by pilmen** [DeclarativeHub/Bond#592]
Is there any way to use custom UITableViewCell loaded from xib?

**Comment by jsembdner** [comment]
I tried this using the CustomBinder as described [here](https://github.com/DeclarativeHub/Bond/blob/master/Documentation/DataSourceSignals.md), because I also want to show a section header.
After binding my custom cell class, only the standard cells are created. The `TableViewBinderDataSource` seems to register new cells which causes Bond to initialize my CustomCell not with the storyboard initializers.

The only way I could make it work is using the tableview bind and dequeueing my own cells in the closure. But if you use this approach, then you can't change other TableViewDataSource delegates e.g. the section header.

**Comment by pilmen** [comment]
Pull request with these improvements was merged into master branch. So I think we can expect this functionality in next version.

**Comment by pilmen** [comment]
One more thing Custom Cell identifier should match Cell's class name.

**Comment by srdanrasic** [comment]
Thanks @pilmen for contributing support for this!
