### ISSUE TITLE
How to bind a signal of MutableObservableArray(s) to a MutableObservableArray2D ?

### ISSUE THREAD

**Issue by npvisual** [DeclarativeHub/Bond#597]
### Context

I have 2 MutableObservableArray (with identical element types). Each array will change over time and I would like to feed them to a MutableObservableArray2D. That array, in turn, will be fed to a UITableView and would, in this particular case, have 2 sections.

So is this possible ?

### Example

This is so far what I narrowed it down to as the most likely candidate, but it's still not working : 

```
        arrayA
            .combineLatest(with: arrayB)
            .map { ($0.collection, $1.collection) }
            .map { [("A", $0), ("B", $1)] }
            .bind(to: AB2DArray)
```

At the moment I am getting the following error : 

```
Cannot convert value of type 'MutableObservableArray2D<String, String>' (aka 'Property<TreeChangeset<TreeArray<Array2DElement<String, String>>>>') to expected argument type 'UIPickerView'
```

Any ideas ?

**Comment by srdanrasic** [comment]
It's not as easy as it seems.

`MutableObservableArray<T>` emits events of the element type `OrderedCollectionChangeset<[T]>`. The changeset contains both the collection (array) itself, as well as the description of changes (diff).

To merge two or more observable arrays into one 2D array you have to merge one or more `OrderedCollectionChangeset<[T]>` into one `TreeChangeset<Array2D<U, T>>`. 

We can start by doing the following

```swift
let a = MutableObservableArray([1, 2, 3])
let b = MutableObservableArray([10, 20, 30])

let ab = a.combineLatest(with: b) { (a: OrderedCollectionChangeset<[Int]>, b: OrderedCollectionChangeset<[Int]>) -> TreeChangeset<Array2D<String, Int>> in
    let array2D = Array2D(sectionsWithItems: [("A", a.collection), ("B", b.collection)])
    let diff = OrderedCollectionDiff<IndexPath>() // empty diff
    return TreeChangeset(collection: array2D, diff: diff)
}
```

You can then bind `ab` signal to a table or a collection view and you'll get two sections. You can also bind it to a `MutableObservableArray2D` instance, although it's not necessary just for the sake of the table/collection view bindings. 

This will work, however each change to any of the source arrays will trigger table/collection view reload. You won't get fine-grained updates. The reason is that we've ignored diffs from `a` and `b`, we are sending just the empty diff and the empty diff makes the view reload the data. 

To improve, we should merge the diffs from the source arrays into a 2D array diff, i.e. a tree diff. Source array diffs are of the type `OrderedCollectionDiff<Int>`. We need to merge those into single `OrderedCollectionDiff<IndexPath>` diff.

Diffs are just arrays of indices that describe changes. We need to transform `Int` indices that refer to source arrays into `IndexPath` indices that refer to the destination 2D array. There is a `map` on the diff type that maps indices so we can use that. It idea here is to group arrays into sections in order they are passed into.

Let's implement this in a convenience initializer of `OrderedCollectionDiff`

```swift
extension OrderedCollectionDiff where Index == IndexPath {

    init(sectionArraysDiffs diffs: [OrderedCollectionDiff<Int>]) {
        let diffs = diffs.enumerated().map { (pair: (Int, OrderedCollectionDiff<Int>)) -> OrderedCollectionDiff<IndexPath> in
            let section = pair.0
            let diff = pair.1
            return diff.map { IndexPath(item: $0, section: section) }
        }
        self.init(
            inserts: diffs.flatMap { $0.inserts },
            deletes: diffs.flatMap { $0.deletes },
            updates: diffs.flatMap { $0.updates },
            moves: diffs.flatMap { $0.moves }
        )
    }
}
```

Now we can do

```swift
let ab = a.combineLatest(with: b) { (a: OrderedCollectionChangeset<[Int]>, b: OrderedCollectionChangeset<[Int]>) -> TreeChangeset<Array2D<String, Int>> in
    let array2D = Array2D(sectionsWithItems: [("A", a.collection), ("B", b.collection)])
    let diff = OrderedCollectionDiff<IndexPath>(sectionArraysDiffs: [a.diff, b.diff])
    return TreeChangeset(collection: array2D, diff: diff)
}
```

and our `ab` signal will then contain the fine-grained changes (diff) too. 

To make things nicer, we could make a function that can combine N observable array signals into a single 2D array signal:

```swift
func combineIntoArray2DChangeset<S: SignalProtocol, T>(_ signals: [S], sections: [T]) -> Signal<TreeChangeset<Array2D<T, S.Element.Collection.Element>>, S.Error> where S.Element: OrderedCollectionChangesetProtocol, S.Element.Collection.Index == Int {
    return combineLatest(signals.map { $0.toSignal() }, combine: { (changesets) -> TreeChangeset<Array2D<T, S.Element.Collection.Element>> in
        let sectionsWithItems = Array(zip(sections, changesets.map { Array($0.collection) }))
        let array2D = Array2D(sectionsWithItems: sectionsWithItems)
        let diff = OrderedCollectionDiff(sectionArraysDiffs: changesets.map { $0.diff })
        return TreeChangeset(collection: array2D, diff: diff)

    })
}
```

It's a bit uglier than I wanted it to be, but it enables us to do the following:

```swift
let a = MutableObservableArray([1, 2, 3])
let b = MutableObservableArray([10, 20, 30])

let ab = combineIntoArray2DChangeset([a, b], sections: ["A", "B"])

ab.bind(to: tableView, cellType: Cell.self) { (cell, item) in
    // todo
}
```

**Comment by npvisual** [comment]
Great ! Thanks a lot for the detailed explanation and code. This works really well.

**Comment by npvisual** [comment]
Would there be a way to make this more generic down the road ? I.e. by adding it to a MutableObservableArray's combine operation (so they can be chained) ? Something along the lines of : 
```
MutableObservableArray.combine(with:sections:)
```

**Comment by srdanrasic** [comment]
At this point I don't have something like that in plan as it does not seems the be general enough.
